### PR TITLE
Verify steps update

### PR DESCRIPTION
**Pull request by tkobayas**
Updated the verify steps for reviewer's convenience.

### CODE REVIEW

**Comment by LightGuard** [comment]
I thought we had a .rat-excludes file. Shouldn't that be used?

**Comment by tkobayas** [comment]
We want to verify all files in our first attempt of thorough license check. In the future (10.1.0 or rc5), we can use .rat-excludes to exclude confirmed files.

**Comment by tkobayas** [comment]
Indeed, I have filed https://github.com/apache/incubator-kie-issues/issues/1613 to ease the release verification step. But while working on the license fixes, I realized that "excluded files" are the important files to check.

**Review by mariofusco — APPROVED** [review]

**Review by jomarko — APPROVED** [review]
I agree with the first release, we can ask people to not use `.rat-excludes` files. Yes, then once release is approved, we can assume our exclude files are correct, and we can start to use them, we do not need more verify their correctness.

Also I think we can be much more confident about the `.rat-excludes` files once we start to use apache-rat@v0.17, as that version has support for full patch in the exclude file. See my issue for future improvement https://github.com/apache/incubator-kie-issues/issues/1670

**Pull request merged**
